
name: Build Geode Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Android
            os: ubuntu-latest
            target: android
          - name: Windows
            os: windows-latest
            target: win

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22

    - name: Build Mod
      uses: geode-sdk/build-geode-mod@main
      with:
        target: ${{ matrix.config.target }}
        # Принудительно настраиваем сборку через xmake вместо CMake
        build-config: Release
        cli: latest

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: geode-mod-${{ matrix.config.target }}
        path: |
          build/**/*.geode
          **/*.geode
