name: Build Geode Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Mod
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Mod for Android
      uses: geode-sdk/build-geode-mod@main
      with:
        # Принудительно отключаем CMake и переводим сборку на Xmake
        build-config: Release

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: my-own-geode-mod
        path: "build/**/*.geode"
