name: Build Geode Mod

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Android
            os: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Mod
      uses: geode-sdk/build-geode-mod@main

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: geode-mod-android
        path: "build/**/*.geode"
